---

- name: present | Docker installation script is present
  environment: "{{ cloudkit_environment }}"
  get_url:
    url: https://get.docker.com/
    dest: /var/tmp/install_docker.sh
    mode: "700"

- name: present | Docker is installed
  command: /var/tmp/install_docker.sh
  args:
    creates: /usr/bin/docker

- name: present | Docker configuration is present
  template:
    src: docker.j2
    dest: /etc/default/docker
    mode: ???
    owner: ???
    group: ???
  notify:
  - cloudkit_reload_docker

- name: present | Docker service is started
  when: cloudkit_docker_autostart
  service:
    name: docker
    state: started
    enabled: yes
