---

- debug:
    msg: |
      ************************
      * docker state=present *
      ************************

# this is currently broken on Debian 7 as the CA is missing apparently
# - name: present | Docker installation script is present
#   environment: "{{ cloudkit_environment }}"
#   get_url:
#     url: https://get.docker.com/
#     dest: /var/tmp/install_docker.sh
#     mode: "700"

- name: Docker installation script is present
  environment: "{{ cloudkit_environment }}"
  command: "curl -sSL https://get.docker.com/ -o {{ cloudkit_docker_installer_path }}"
  args:
    creates: "{{ cloudkit_docker_installer_path }}"

- name: Docker is installed
  command: "/bin/sh {{ cloudkit_docker_installer_path }}"
  args:
    creates: /usr/bin/docker

- name: Docker configuration is present
  template:
    src: docker.j2
    dest: /etc/default/docker
    mode: "644"
    owner: root
    group: root
  notify:
  - cloudkit_reload_docker

- name: Docker service is started
  when: cloudkit_docker_autostart
  service:
    name: docker
    state: started
    enabled: yes
