---
- fail:
    msg: unsupported platform -- please contact the role maintainer for support
  when: ansible_distribution not in ['Ubuntu', 'Debian']
- include: docker_absent.yml
  name: Taskfile docker_absent.yml is included
  when: cloudkit_docker_state == "absent"
- include: docker_present.yml
  name: Taskfile docker_present.yml is included
  when: cloudkit_docker_state == "present"
