---

# DOC: https://github.com/retspen/webvirtmgr/wiki/Install-WebVirtMgr

- debug:
    msg: |
      ****************************
      * webvirtmgr state=present *
      ****************************

- name: Webvirtmgr support packages are present
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if cloudkit_update else 'present' }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - git
  - python-pip
  - python-libvirt
  - python-libxml2
  - novnc
  - supervisor
  - nginx

- name: /opt directory is present
  file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: "755"

- name: Webvirtmgr source repository is present
  git:
    repo: https://github.com/retspen/webvirtmgr.git
    dest: /opt/webvirtmgr

- name: Webvirtmgr source repository is set
  command: chown -R www-data.www-data /opt/webvirtmgr

- name: Webvirtmgr python requirements are present
  pip:
    requirements: /opt/webvirtmgr/requirements.txt

- name: Webvirtmgr Supervisor configuration is present
  copy:
    src: supervisor.webvirtmgr.conf
    dest: /etc/supervisor/conf.d/webvirtmgr.conf
    owner: root
    group: root
    mode: "644"
  notify:
  - cloudkit_reload_supervisor

- name: Supervisor service is started
  service:
    name: supervisor
    state: started
