---

# DOC: https://github.com/retspen/webvirtmgr/wiki/Install-WebVirtMgr

- name: present | Webvirtmgr support packages are present
  apt:
    name: "{{ item }}"
    state: "{{ 'latest' if cloudkit_update else 'present' }}"
    update_cache: yes
    cache_valid_time: 3600
  with_items:
  - git
  - python-pip
  - python-libvirt
  - python-libxml2
  - novnc
  - supervisor
  - nginx

- name: present | /opt directory is present
  file:
    path: /opt
    state: directory
    owner: root
    group: root
    mode: "755"

- name: present | Webvirtmgr source repository is present
  git:
    repo: https://github.com/retspen/webvirtmgr.git
    dest: /opt/webvirtmgr

- name: present | Webvirtmgr python requirements are present
  pip:
    requirements: /opt/webvirtmgr/requirements.txt

- name: present | Webvirtmgr source repository is  
  command: chown -R www-data.www-data /opt/webvirtmgr


